const prettierOffRules = require('stylelint-config-prettier');

const offRules = {
  'function-calc-no-unspaced-operator': '和function-calc-no-invalid重复',
  'color-named': '不做限制',
  'color-no-hex': '不做限制',
  'function-blacklist': '不做限制',
  'function-url-scheme-blacklist': '不做限制',
  'function-url-scheme-whitelist': '不做限制',
  'function-whitelist': '不做限制',
  'keyframes-name-pattern': '不做限制',
  'time-min-milliseconds': '不做限制',
  'unit-blacklist': '不做限制',
  'unit-whitelist': '不做限制',
  'value-no-vendor-prefix': '不做限制',
  'custom-property-pattern': '不做限制',
  'property-blacklist': '不做限制',
  'property-no-vendor-prefix': '不做限制',
  'property-whitelist': '不做限制',
  'declaration-property-unit-blacklist': '不做限制',
  'declaration-property-unit-whitelist': '不做限制',
  'declaration-property-value-blacklist': '不做限制',
  'declaration-property-value-whitelist': '不做限制',
  'selector-attribute-operator-blacklist': '不做限制',
  'selector-attribute-operator-whitelist': '不做限制',
  'selector-class-pattern': '不做限制',
  'selector-combinator-blacklist': '不做限制',
  'selector-combinator-whitelist': '不做限制',
  'selector-id-pattern': '不做限制',
  'selector-max-attribute': '不做限制',
  'selector-max-class': '不做限制',
  'selector-max-combinators': '不做限制',
  'selector-max-compound-selectors': '不做限制',
  'selector-max-id': '不做限制',
  'selector-max-pseudo-class': '不做限制',
  'selector-max-specificity': '不做限制',
  'selector-max-type': '不做限制',
  'selector-max-universal': '不做限制',
  'selector-nested-pattern': '不做限制',
  'selector-no-vendor-prefix': '不做限制',
  'selector-pseudo-class-blacklist': '不做限制',
  'selector-pseudo-class-whitelist': '不做限制',
  'selector-pseudo-element-blacklist': '不做限制',
  'selector-pseudo-element-whitelist': '不做限制',
  'media-feature-name-blacklist': '不做限制',
  'media-feature-name-no-vendor-prefix': '不做限制',
  'media-feature-name-value-whitelist': '不做限制',
  'media-feature-name-whitelist': '不做限制',
  'custom-media-pattern': '不做限制',
  'at-rule-blacklist': '不做限制',
  'at-rule-no-vendor-prefix': '不做限制',
  'at-rule-whitelist': '不做限制',
  'comment-word-blacklist': '不做限制',
  'color-hex-length': '不做限制',
  'font-weight-notation': '不做限制',
  'function-whitespace-after': '不做限制',
  'custom-property-empty-line-before': '不做限制',
  'declaration-empty-line-before': '不做限制',
  'selector-attribute-operator-space-after': '不做限制',
  'selector-attribute-operator-space-before': '不做限制',
  'media-feature-range-operator-space-after': '不做限制',
  'media-feature-range-operator-space-before': '不做限制',
  'comment-empty-line-before': '不做限制',
  'comment-whitespace-inside': '不做限制',
  'no-missing-end-of-source-newline': '不做限制',
  'no-empty-first-line': '不做限制',
};
module.exports = Object.keys(offRules).concat(
  Object.keys(prettierOffRules.rules),
);
